# Generated by Django 3.0.8 on 2020-08-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('last_login', models.DateTimeField()),
                ('login_count', models.IntegerField()),
                ('project_count', models.IntegerField()),
            ],
        ),
    ]
